package com.tyut.apps.gss.mapper;

import com.tyut.apps.gss.bean.Detailed;
import com.tyut.apps.gss.bean.DetailedExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DetailedMapper {

    /**
     * 根据baseId查询详细信息
     */
    Detailed selectDetailedByBaseId(Integer baseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    long countByExample(DetailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int deleteByExample(DetailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int deleteByPrimaryKey(Integer stid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int insert(Detailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int insertSelective(Detailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    List<Detailed> selectByExample(DetailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    Detailed selectByPrimaryKey(Integer stid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") Detailed record, @Param("example") DetailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int updateByExample(@Param("record") Detailed record, @Param("example") DetailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int updateByPrimaryKeySelective(Detailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int updateByPrimaryKey(Detailed record);
}