package com.tyut.apps.gss.mapper;

import com.tyut.apps.gss.bean.Grant;
import com.tyut.apps.gss.bean.GrantExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GrantMapper {

    /**
     * 根据baseId查询助学金的信息
     */
    Grant selectGrantByBaseId(Integer baseId);

    /**
     * 更改助学金的状态
     */
    void updateGrantStatus(Integer gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grants
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    long countByExample(GrantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grants
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int deleteByExample(GrantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grants
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int deleteByPrimaryKey(Integer gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grants
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int insert(Grant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grants
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int insertSelective(Grant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grants
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    List<Grant> selectByExample(GrantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grants
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    Grant selectByPrimaryKey(Integer gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grants
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") Grant record, @Param("example") GrantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grants
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int updateByExample(@Param("record") Grant record, @Param("example") GrantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grants
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int updateByPrimaryKeySelective(Grant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grants
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int updateByPrimaryKey(Grant record);
}