package com.tyut.apps.gss.mapper;

import com.tyut.apps.gss.bean.Scholarship;
import com.tyut.apps.gss.bean.ScholarshipExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScholarshipMapper {

    /**
     * 根据baseID查询奖学金的信息
     */
    Scholarship selectScholarshipByBaseId(Integer baseId);

    /**
     * 根据baseId更改奖学金申请的状态
     * @param scid
     */
    void updateScholarshipStatus(Integer scid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    long countByExample(ScholarshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int deleteByExample(ScholarshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int deleteByPrimaryKey(Integer scid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int insert(Scholarship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int insertSelective(Scholarship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    List<Scholarship> selectByExample(ScholarshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    Scholarship selectByPrimaryKey(Integer scid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") Scholarship record, @Param("example") ScholarshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int updateByExample(@Param("record") Scholarship record, @Param("example") ScholarshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int updateByPrimaryKeySelective(Scholarship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    int updateByPrimaryKey(Scholarship record);
}