package com.tyut.apps.gss.bean;

public class Academy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column academy.aid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column academy.aname
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private String aname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column academy.aid
     *
     * @return the value of academy.aid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column academy.aid
     *
     * @param aid the value for academy.aid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column academy.aname
     *
     * @return the value of academy.aname
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column academy.aname
     *
     * @param aname the value for academy.aname
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }
}