package com.tyut.apps.gss.bean;

import java.util.Date;

public class Base {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.bid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.createdate
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.email
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.gender
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.name
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.password
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.phone
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.qq
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.sno
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private String sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.a_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private Integer aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.c_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.r_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private Integer rId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.bid
     *
     * @return the value of base.bid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.bid
     *
     * @param bid the value for base.bid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.createdate
     *
     * @return the value of base.createdate
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.createdate
     *
     * @param createdate the value for base.createdate
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.email
     *
     * @return the value of base.email
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.email
     *
     * @param email the value for base.email
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.gender
     *
     * @return the value of base.gender
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.gender
     *
     * @param gender the value for base.gender
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.name
     *
     * @return the value of base.name
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.name
     *
     * @param name the value for base.name
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.password
     *
     * @return the value of base.password
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.password
     *
     * @param password the value for base.password
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.phone
     *
     * @return the value of base.phone
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.phone
     *
     * @param phone the value for base.phone
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.qq
     *
     * @return the value of base.qq
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.qq
     *
     * @param qq the value for base.qq
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.sno
     *
     * @return the value of base.sno
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.sno
     *
     * @param sno the value for base.sno
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.a_id
     *
     * @return the value of base.a_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.a_id
     *
     * @param aId the value for base.a_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.c_id
     *
     * @return the value of base.c_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.c_id
     *
     * @param cId the value for base.c_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.r_id
     *
     * @return the value of base.r_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.r_id
     *
     * @param rId the value for base.r_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }
}