package com.tyut.apps.gss.bean;

public class Cla {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cla.cid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cla.cname
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private String cname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cla.cid
     *
     * @return the value of cla.cid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cla.cid
     *
     * @param cid the value for cla.cid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cla.cname
     *
     * @return the value of cla.cname
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cla.cname
     *
     * @param cname the value for cla.cname
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }
}