package com.tyut.apps.gss.bean;

public class Detailed {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed.stid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private Integer stid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed.address
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed.bankcard
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private String bankcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed.idcard
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed.base_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private Integer baseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed.stid
     *
     * @return the value of detailed.stid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public Integer getStid() {
        return stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed.stid
     *
     * @param stid the value for detailed.stid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setStid(Integer stid) {
        this.stid = stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed.address
     *
     * @return the value of detailed.address
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed.address
     *
     * @param address the value for detailed.address
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed.bankcard
     *
     * @return the value of detailed.bankcard
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public String getBankcard() {
        return bankcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed.bankcard
     *
     * @param bankcard the value for detailed.bankcard
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setBankcard(String bankcard) {
        this.bankcard = bankcard == null ? null : bankcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed.idcard
     *
     * @return the value of detailed.idcard
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed.idcard
     *
     * @param idcard the value for detailed.idcard
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed.base_id
     *
     * @return the value of detailed.base_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public Integer getBaseId() {
        return baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed.base_id
     *
     * @param baseId the value for detailed.base_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setBaseId(Integer baseId) {
        this.baseId = baseId;
    }
}