package com.tyut.apps.gss.bean;

public class Grant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grants.gid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grants.reason
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grants.status
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grants.base_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private Integer baseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grants.gid
     *
     * @return the value of grants.gid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grants.gid
     *
     * @param gid the value for grants.gid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grants.reason
     *
     * @return the value of grants.reason
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grants.reason
     *
     * @param reason the value for grants.reason
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grants.status
     *
     * @return the value of grants.status
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grants.status
     *
     * @param status the value for grants.status
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grants.base_id
     *
     * @return the value of grants.base_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public Integer getBaseId() {
        return baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grants.base_id
     *
     * @param baseId the value for grants.base_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setBaseId(Integer baseId) {
        this.baseId = baseId;
    }

    @Override
    public String toString() {
        return "Grant{" +
                "gid=" + gid +
                ", reason='" + reason + '\'' +
                ", status=" + status +
                ", baseId=" + baseId +
                '}';
    }
}