package com.tyut.apps.gss.bean;

public class Scholarship {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scholarship.scid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private Integer scid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scholarship.grade
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scholarship.status
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scholarship.base_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    private Integer baseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scholarship.scid
     *
     * @return the value of scholarship.scid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public Integer getScid() {
        return scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scholarship.scid
     *
     * @param scid the value for scholarship.scid
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setScid(Integer scid) {
        this.scid = scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scholarship.grade
     *
     * @return the value of scholarship.grade
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scholarship.grade
     *
     * @param grade the value for scholarship.grade
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scholarship.status
     *
     * @return the value of scholarship.status
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scholarship.status
     *
     * @param status the value for scholarship.status
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scholarship.base_id
     *
     * @return the value of scholarship.base_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public Integer getBaseId() {
        return baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scholarship.base_id
     *
     * @param baseId the value for scholarship.base_id
     *
     * @mbg.generated Mon Mar 16 20:41:55 CST 2020
     */
    public void setBaseId(Integer baseId) {
        this.baseId = baseId;
    }
}